language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"
install:
  - pip install -r requirements/default.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
  - python -m tests.__main__
